version: '3.8'

services:
  # Backend Laravel Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: news-backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor  # Prevents overwriting vendor directory
      - /var/www/html/node_modules  # Prevents overwriting node_modules
    networks:
      - news-network
    depends_on:
      - db

  # Frontend React Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: news-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevents overwriting node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true  # Enable hot reload on Windows/MacOS
      - WATCHPACK_POLLING=true    # Enable hot reload for newer versions
      - WDS_SOCKET_PORT=0         # Required for newer Create React App versions
    networks:
      - news-network
    command: npm start   # Override Dockerfile CMD to use development server

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: news-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - news-network
    depends_on:
      - backend

  # PostgreSQL Service
  db:
    image: postgres:15-alpine
    container_name: news-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: news_aggregator
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - news-network
    ports:
      - "5432:5432"

networks:
  news-network:
    driver: bridge

volumes:
  postgres_data: